name: Deploy Application to live Server

on:
  push:
    branches: ["live"]
  pull_request:
    branches: ["live"]

jobs:
  live-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd domains/ouiverte.fr/public_html
            git fetch --all
            git reset --hard origin/live
            git pull
            composer2 install --no-dev --optimize-autoloader
            php artisan optimize:clear
            php artisan migrate --force
